apiVersion: v1
kind: Service
metadata:
  name: telecom-cdr
  labels:
    app: telecom-cdr
spec:
  type: ClusterIP
  selector:
    app: telecom-cdr
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
